# Generated by Django 5.0.4 on 2024-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='booking_app_last_na_23b279_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['age'], name='age_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sex'], name='sex_idx'),
        ),
    ]
