# Generated by Django 5.0.4 on 2024-05-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_user_booking_app_last_na_23b279_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='booking_app_last_na_23b279_idx',
        ),
    ]
