# Generated by Django 5.0.4 on 2024-06-05 18:11

import booking_app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_user_booking_app_last_na_23b279_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobbies', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='hotelowner',
            options={'verbose_name': 'Владельцы', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='booking_app.hotelowner', verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(null=True, validators=[booking_app.validators.validate_hotel_stars], verbose_name='количество звёзд'),
        ),
    ]
