# Generated by Django 5.0.4 on 2024-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_hobby_options_alter_hotelowner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to='hotels_photo/', verbose_name='фото'),
        ),
    ]
