# Generated by Django 5.0.4 on 2024-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_hotel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
