# Generated by Django 5.0.4 on 2024-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_personqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotels_photo/', verbose_name='фото'),
        ),
    ]
